---
title: "Demo_stGrads_HD"
author: "Yifan Fu"
date: "2025-04-06"
output: html_document
---

### 0x01 loading environment

```{r,echo=F,warning=FALSE}
set.seed(1113)
library(Seurat)
library(ggsci)

library(stGrads)
library(stringr)
options(future.globals.maxSize= 10*1024^3)
```

### 0x02 loading demo data

```{r,echo=T,warning=F}
st.hd <- readRDS('HD_demo_1.rds')

SpatialDimPlot(st.hd,group.by = 'first_type',image.scale = 'hires',
               crop = T,shape=22,
               pt.size.factor =80* st.hd@images[["slice1"]]@scale.factors[["hires"]],
               alpha =0.75)+scale_fill_manual(values =c('#FFF68F','#CDBE70',
                                                        '#CD2626','#008B8B','#8B3A3A') )


```

### 0x03 Calculating distance matrix

```{r, echo=T,warning=F}
dis_mtx.Duct2_myCAF <-CalcNearDis_HD(st.hd,celltype = 'first_type',query_celltype = 'Duct2',
                    pheno_choose = 'myCAF',max.r = 100,resolution = 8)
dis_mtx.Duct2_Mp <-CalcNearDis_HD(st.hd,celltype = 'first_type',query_celltype = 'Duct2',
                    pheno_choose = 'Macrophage',max.r = 100,resolution = 8)
dis_mtx.Duct2_myCAF$ref='myCAF'
dis_mtx.Duct2_Mp$ref='Macrophage'
dff <- rbind(dis_mtx.Duct2_myCAF,dis_mtx.Duct2_Mp)
dff$distance <- as.numeric(dff$distance)
ggplot(dff)+geom_density(aes(x=distance,colour=ref),linewidth=2)+theme_bw()+
  labs(title='Duct 2 cell -> myCAF/Macrophage (r = 100um)',x='Distance (um)',y='Density')+theme(legend.position = 'none')+
  scale_color_manual(values = c('#CD2626','#008B8B'))


```

### 0x03-2 [Optional]Calculating strength matrix

```{r, echo=T,warning=F}
stg_mtx.Duct2_myCAF <-CalcNearDis_HD(st.hd,celltype = 'first_type',query_celltype = 'Duct2',
                    pheno_choose = 'myCAF',max.r = 100,resolution = 8,calc.strength = T,model = 'Linear')
stg_mtx.Duct2_Mp <-CalcNearDis_HD(st.hd,celltype = 'first_type',query_celltype = 'Duct2',
                    pheno_choose = 'Macrophage',max.r = 100,resolution = 8,calc.strength = T,model = 'Linear')
stg_mtx.Duct2_myCAF$ref='myCAF'
stg_mtx.Duct2_Mp$ref='Macrophage'
dff.stg <- rbind(stg_mtx.Duct2_myCAF,stg_mtx.Duct2_Mp)
dff.stg$strength.sum <- dff.stg$strength.sum/max(dff.stg$strength.sum)
# ggplot(dff.stg)+geom_density(aes(x=strength.sum,colour=ref),linewidth=2)+theme_bw()+
#   labs(title='Duct 2 cell -> myCAF/Macrophage (r = 100um)',x='Relative Strength',y='Density')+theme(legend.position = 'none')+
#   scale_color_manual(values = c('#CD2626','#008B8B'))


```

### 0x04 Visualization

```{r, echo=T,warning=F}
PlotNearDis(st.hd,nearest_ref_info = dis_mtx.Duct2_Mp,max.dis = 100,color = c('darkred','gray'),shape = 22,img.use = 'hires',image.alpha = 1,
            pt.size.factor = 80* sce1@images[["slice1"]]@scale.factors[["hires"]])+labs(title='Duct 2 cell -> myCAF (r = 100um)')

PlotStrengthDis(st.hd,nearest_ref_info = stg_mtx.Duct2_Mp,max.dis = 100,color = c('gray','darkgreen'),shape = 22,img.use = 'hires',image.alpha = 1,
                pt.size.factor = 80* sce1@images[["slice1"]]@scale.factors[["hires"]])+labs(title='Duct 2 cell -> myCAF (r = 100um)')

```

### 0x05 Find DRGs

```{r, echo=T,warning=F}
st.hd <- NormalizeData(st.hd)
DRGs <- CalcDRG(st.hd,nearest_ref_info = dis_mtx.Duct2_Mp,layer = 'data',assay = 'Spatial',
                  pthresh = 1,log.trans = F,filt_root = T,filt_far = 100)
head(DRGs)
PlotDRGs(DRGs)
```

### 0x06 Visualization Dis-Expr

```{r,echo=T,warning=F}

PlotDisExpr(seurat.obj = st.hd,nearest_ref_info = dis_mtx.Duct2_Mp,ref_col = 'distance',assay = 'Spatial',
            gene ='SPARC',col = 'darkred',log.trans = F,filt_root =T,filt_far = 100)

PlotDisExpr(seurat.obj = st.hd,nearest_ref_info = dis_mtx.Duct2_Mp,ref_col = 'distance',assay = 'Spatial',
            gene ='APOL1',col='darkgreen',log.trans = F,filt_root =T,filt_far = 100)

```
